### ISSUE TITLE
[Beta] Console Stack creation fails

### ISSUE THREAD

**Issue by CasperEngl** [anomalyco/console#2]
So I've updated my payment preferences to make sure there are no billing issues, but I'm getting these errors on the deployed Console stack on us-east-1 N. Virginia. 

![image](https://github.com/serverless-stack/console/assets/11478629/af267f1b-c644-4bd7-a20f-dc4d1f5a0bb5)

Nothing here is clickable.

I haven't created any app stacks which may be required for the Console stack to be created.

So I don't really know where to go from here.

**Comment by thdxr** [comment]
didn't see this till now - since it's pretty old i imagine we fixed this issue so i'm going to close it - feel free to reoepn
