### ISSUE TITLE
Link to logs for AuthAuthenticator not showing

### ISSUE THREAD

**Issue by mattrobrob** [anomalyco/console#22]
There's a slight rendering issue in the list of resources that have logs. The name of the function isn't showing so the link isn't clickable. Inspecting the element shows the link is there but the element is just hidden because the name hasn't rendered, leaving an empty anchor tag.

[Offending LOC](https://github.com/sst/console/blob/dev/packages/web/workspace/src/pages/workspace/stage/logs/list.tsx#L302)

<img width="817" alt="Screenshot 2024-07-27 at 23 45 02" src="https://github.com/user-attachments/assets/da94bd8e-a04f-4b96-9869-9a12ecb1b756">
<img width="513" alt="Screenshot 2024-07-27 at 23 45 24" src="https://github.com/user-attachments/assets/16177706-cad3-4205-bc0d-7578b475eef5">

**Comment by jayair** [comment]
Thanks! I'll take a look.

**Comment by mattrobrob** [comment]
Appears to be fixed!
