### ISSUE TITLE
Receiving alerts from deleted workspace

### ISSUE THREAD

**Issue by fschmtt** [anomalyco/console#27]
Hey there,

I don't know where else to raise this issue, as I've already tried to contact you via hello[ at ]sst.dev but got no response.

I'm still receiving alerts for a workspace I have deleted and, as it is deleted, I can obviously no longer access it to change the alerting preferences 😅 

IDK if this is a general bug or only affecting me in this specific case.

Thanks for your help! 😊

**Comment by jayair** [comment]
Weird that your email didn't get through.

What's the name of the old workspace?

**Comment by fschmtt** [comment]
It’s “fschmtt-swag”.

**Comment by fschmtt** [comment]
I haven't been getting any mails from this workspace in 4 days, has the issue been resolved? 😄
