### ISSUE TITLE
Unable to invite user to workspace and can't add billing details

### ISSUE THREAD

**Issue by AlbertoV5** [anomalyco/console#29]
Looks like emails aren't being sent for the invites. Also the Add Billing Details button takes me to: `console.sst.dev/{app-name}/undefined`
:(
<img width="733" alt="Screenshot 2024-11-11 at 19 00 06" src="https://github.com/user-attachments/assets/814cd244-b843-4eb6-bb32-4db380d3b768">

**Comment by thdxr** [comment]
should be fixed now sorry abut that
