### ISSUE TITLE
Autodeploy Docker "Too Many Requests" error - SST Console issue, or my issue?

### ISSUE THREAD

**Issue by ceigey** [anomalyco/console#30]
Hi all, not sure where this issue stems from.

I've got a Cluster component in an SST app which uses the amazoncorretto:21 image.

Autodeploy failed with this new and unexpected error:

> failed to solve: amazoncorretto:21: failed to resolve source metadata for docker.io/library/amazoncorretto:21: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/amazoncorretto/manifests/sha256:c822834af06f45fb263c9dc719e85954e101e8fb706f3b9bdc2b36fab3844341: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

Following the URL gives:

> Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours

I'm certainly not using even 5 or 10 pulls, which makes me think this is a shared allowance across all SST console users on a certain instance?

I've heard people recommend using ECR instead due to these pull limits, the AWS documentation appears to just mention this way of pulling their images:

```bash
docker pull public.ecr.aws/registry_alias/repository:tag
```

(per [this link](https://docs.aws.amazon.com/AmazonECR/latest/public/docker-pull-ecr-image.html#:~:text=To%20pull%20a%20public%20image%20from%20the%20Amazon%20ECR%20Public%20Gallery&text=You%20can%20view%20the%20available,are%20valid%20for%2012%20hours.))

But I'm guessing for use with SST Autodeploy where we don't have arbitrary pipeline commands, something like this (based on [this tangential stackoverflow answer](https://stackoverflow.com/a/58312141)) might be better?:

```diff
- FROM amazoncorretto:21
+ FROM public.ecr.aws/amazoncorretto/amazoncorretto:21
```

_Note, I've only ever used Docker Hub for base images before, so I have yet to try the second version, just not in a position to try it right now..._

**Comment by fwang** [comment]
@ceigey we recently pushed out a change to the `Cluster` to cache image layers to ECR by default. It should drastically reduce the number of docker pulls.

Give the latest version a try. Please reopen this if this still happens.

**Comment by ceigey** [comment]
Hi @fwang, apologies for the late reply (holiday season etc). Thank you to you and the team for looking into this and pushing out that change! I'll update if we come across this again.
