### ISSUE TITLE
Create workspace button not responding

### ISSUE THREAD

**Issue by keyserfaty** [anomalyco/console#31]
Trying to create a new account and can't get pass the create workspace step. Adding a new does nothing. No request beign sent to the backend either. Would love to try the console. Thank you 🙏

**Comment by moritzbehnke** [comment]
@keyserfaty I also ran into the issue while wanting to try out `sst console`. I used a quick "workaround" by sending a POST request to `https://api.console.sst.dev/account/workspace` with the Basic Auth token taken from the GET request (accessing `http://console.sst.dev/` after logging in with email) and a body with the format `{"slug":"your-workspace-name"}`. Maybe this works for you as well when you don't want to wait until the from submission is fixed.

**Comment by jayair** [comment]
Sorry about that. Just pushed a fix. Give it a try and let me know?

**Comment by moritzbehnke** [comment]
Just tried and the button works

**Comment by jayair** [comment]
Closing for now
