### ISSUE TITLE
`Functions` list in stack overview is inaccurate

### ISSUE THREAD

**Issue by BLucky-gh** [anomalyco/console#4]
![image](https://github.com/serverless-stack/console/assets/41377306/5b048adc-e362-4e7a-ae27-39c26e9655ee)
there's only 2 functions (plus a NextjsSite), and both of them are python functions. As you see in the screenshot, it shows a bunch of duplicates of one of the functions, and reports all of them as js.

I checked if it maybe reports one per function version, but there's only one version available of that one

**Comment by jayair** [comment]
Just checking, we replied to this on Discord right?

**Comment by BLucky-gh** [comment]
Nope, the one I reposted on discord is a different issue

**Comment by jayair** [comment]
Checking on this, did we resolve it? If not can you post again in the channel and then DM us your workspace name?

**Comment by BLucky-gh** [comment]
nope, I did not post this issue to discord because I was not asked to, and thus it was not resolved. I'm gonna assume from what you said that you need me to post this on discord so here's the link to the thread: 
https://discord.com/channels/983865673656705025/1140560105599930409/1140560105599930409
