### ISSUE TITLE
cannot enter console pin code

### ISSUE THREAD

**Issue by sairajchouhan** [anomalyco/console#6]
when I type the first number in the input the page refreshes with with `?error=invalid_code` in the query params, below is the video showing this behavior

https://github.com/sst/console/assets/57995897/264bbc1c-c0fc-4fc4-a4ef-fae4462603ae

**Comment by jayair** [comment]
Hmm that's weird, thanks for reporting. Which browser version and OS?

**Comment by sairajchouhan** [comment]
Firefox Version 119.0 (64 bit) on Apple M1 Pro running Sonoma 14.0

**Comment by sairajchouhan** [comment]
@jayair I just tried to login from the latest build of chrome and I see the same thing happening, browser does full page reload with with error query param as soon as I type

**Comment by thdxr** [comment]
just pushed a fix!
